-- Loadify Market database bootstrap snapshot — DEPRECATED.
--
-- DO NOT execute this file against any Supabase project.
--
-- The historical single-file schema snapshot was retired because it could drift
-- from production migrations and could reintroduce legacy cross-project database
-- surfaces. The only supported source of truth is now:
--
--   supabase/migrations/
--
-- For a fresh environment, apply the ordered migrations instead of using a
-- consolidated/manual bootstrap script. Keep this file intentionally free of DDL
-- so it cannot recreate retired tables, columns, policies, or integrations.
