-- ================================================================
-- 08_notifications_saved_searches.sql
-- Loadify Market — Notifications & Saved Searches
-- ================================================================
-- NOTE: These tables are now in 05_rfq_messages.sql
-- (wishlists, saved_searches, notifications, notification_settings)
-- This file is kept for reference. No new SQL to run here.
-- ================================================================
-- Tables covered in 05_rfq_messages.sql:
--   wishlists
--   saved_searches
--   notifications
--   notification_settings
