-- ================================================================
-- 09_promotions_featured.sql
-- Loadify Market — Promotions & Featured Listings
-- ================================================================
-- NOTE: These tables are now in:
--   featured_listings, banners → 02_categories_products.sql
--   promoted_listings          → 07_admin_moderation.sql
-- This file is kept for reference. No new SQL to run here.
-- ================================================================
-- Tables covered elsewhere:
--   featured_listings  (02_categories_products.sql)
--   banners            (02_categories_products.sql)
--   promoted_listings  (07_admin_moderation.sql)
