-- Canonical marketplace taxonomy parity: 16 root categories / 96 subcategories.
-- Legacy roots are deactivated rather than deleted so historical product/order references remain intact.

UPDATE categories
SET "isActive" = FALSE
WHERE COALESCE(level, 1) = 1
  AND slug <> ALL (ARRAY['electronics-and-technology', 'clothing-and-apparel', 'home-and-garden', 'health-and-beauty', 'toys-and-games', 'food-and-drink', 'tools-and-diy', 'sports-and-leisure', 'automotive', 'office-and-stationery', 'baby-and-nursery', 'jewellery-and-watches', 'mixed-lots', 'customer-returns', 'overstock', 'clearance-deals']::text[]);

WITH roots(name, slug, sort_order) AS (
  VALUES
    ('Electronics & Technology','electronics-and-technology',1),
    ('Clothing & Apparel','clothing-and-apparel',2),
    ('Home & Garden','home-and-garden',3),
    ('Health & Beauty','health-and-beauty',4),
    ('Toys & Games','toys-and-games',5),
    ('Food & Drink','food-and-drink',6),
    ('Tools & DIY','tools-and-diy',7),
    ('Sports & Leisure','sports-and-leisure',8),
    ('Automotive','automotive',9),
    ('Office & Stationery','office-and-stationery',10),
    ('Baby & Nursery','baby-and-nursery',11),
    ('Jewellery & Watches','jewellery-and-watches',12),
    ('Mixed Lots','mixed-lots',13),
    ('Customer Returns','customer-returns',14),
    ('Overstock','overstock',15),
    ('Clearance Deals','clearance-deals',16)
)
INSERT INTO categories (name, slug, description, "order", "isActive", level, parent_id, "parentId")
SELECT name, slug, name || ' marketplace category', sort_order, TRUE, 1, NULL, NULL
FROM roots
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  "order" = EXCLUDED."order",
  "isActive" = TRUE,
  level = 1,
  parent_id = NULL,
  "parentId" = NULL;

WITH taxonomy(parent_slug, name, slug, sort_order) AS (
  VALUES
    ('electronics-and-technology','Phones & Tablets','electronics-and-technology-phones-and-tablets',101),
    ('electronics-and-technology','Laptops & PCs','electronics-and-technology-laptops-and-pcs',102),
    ('electronics-and-technology','TV & Audio','electronics-and-technology-tv-and-audio',103),
    ('electronics-and-technology','Gaming Consoles','electronics-and-technology-gaming-consoles',104),
    ('electronics-and-technology','Accessories','electronics-and-technology-accessories',105),
    ('electronics-and-technology','Smart Home','electronics-and-technology-smart-home',106),
    ('clothing-and-apparel','Men''s Clothing','clothing-and-apparel-men-s-clothing',201),
    ('clothing-and-apparel','Women''s Clothing','clothing-and-apparel-women-s-clothing',202),
    ('clothing-and-apparel','Children''s Clothing','clothing-and-apparel-children-s-clothing',203),
    ('clothing-and-apparel','Footwear','clothing-and-apparel-footwear',204),
    ('clothing-and-apparel','Accessories & Bags','clothing-and-apparel-accessories-and-bags',205),
    ('clothing-and-apparel','Sportswear','clothing-and-apparel-sportswear',206),
    ('home-and-garden','Furniture','home-and-garden-furniture',301),
    ('home-and-garden','Kitchen & Dining','home-and-garden-kitchen-and-dining',302),
    ('home-and-garden','Bedding & Linen','home-and-garden-bedding-and-linen',303),
    ('home-and-garden','Garden & Outdoor','home-and-garden-garden-and-outdoor',304),
    ('home-and-garden','Lighting','home-and-garden-lighting',305),
    ('home-and-garden','Décor & Accessories','home-and-garden-d-cor-and-accessories',306),
    ('health-and-beauty','Skincare','health-and-beauty-skincare',401),
    ('health-and-beauty','Haircare','health-and-beauty-haircare',402),
    ('health-and-beauty','Makeup & Cosmetics','health-and-beauty-makeup-and-cosmetics',403),
    ('health-and-beauty','Fragrances','health-and-beauty-fragrances',404),
    ('health-and-beauty','Health & Wellness','health-and-beauty-health-and-wellness',405),
    ('health-and-beauty','Personal Care','health-and-beauty-personal-care',406),
    ('toys-and-games','Action Figures','toys-and-games-action-figures',501),
    ('toys-and-games','Board Games','toys-and-games-board-games',502),
    ('toys-and-games','Educational Toys','toys-and-games-educational-toys',503),
    ('toys-and-games','Outdoor Toys','toys-and-games-outdoor-toys',504),
    ('toys-and-games','Dolls & Playsets','toys-and-games-dolls-and-playsets',505),
    ('toys-and-games','Puzzles','toys-and-games-puzzles',506),
    ('food-and-drink','Snacks & Confectionery','food-and-drink-snacks-and-confectionery',601),
    ('food-and-drink','Beverages','food-and-drink-beverages',602),
    ('food-and-drink','Canned & Dry Goods','food-and-drink-canned-and-dry-goods',603),
    ('food-and-drink','Health Foods','food-and-drink-health-foods',604),
    ('food-and-drink','Specialty & Gourmet','food-and-drink-specialty-and-gourmet',605),
    ('food-and-drink','Seasonal','food-and-drink-seasonal',606),
    ('tools-and-diy','Power Tools','tools-and-diy-power-tools',701),
    ('tools-and-diy','Hand Tools','tools-and-diy-hand-tools',702),
    ('tools-and-diy','Plumbing','tools-and-diy-plumbing',703),
    ('tools-and-diy','Electrical','tools-and-diy-electrical',704),
    ('tools-and-diy','Paint & Decorating','tools-and-diy-paint-and-decorating',705),
    ('tools-and-diy','Fixings & Hardware','tools-and-diy-fixings-and-hardware',706),
    ('sports-and-leisure','Fitness Equipment','sports-and-leisure-fitness-equipment',801),
    ('sports-and-leisure','Cycling','sports-and-leisure-cycling',802),
    ('sports-and-leisure','Camping & Hiking','sports-and-leisure-camping-and-hiking',803),
    ('sports-and-leisure','Water Sports','sports-and-leisure-water-sports',804),
    ('sports-and-leisure','Team Sports','sports-and-leisure-team-sports',805),
    ('sports-and-leisure','Leisure & Travel','sports-and-leisure-leisure-and-travel',806),
    ('automotive','Car Parts','automotive-car-parts',901),
    ('automotive','Car Accessories','automotive-car-accessories',902),
    ('automotive','Cleaning & Valeting','automotive-cleaning-and-valeting',903),
    ('automotive','Tools & Equipment','automotive-tools-and-equipment',904),
    ('automotive','Oils & Fluids','automotive-oils-and-fluids',905),
    ('automotive','Tyres & Wheels','automotive-tyres-and-wheels',906),
    ('office-and-stationery','Office Furniture','office-and-stationery-office-furniture',1001),
    ('office-and-stationery','Printers & Ink','office-and-stationery-printers-and-ink',1002),
    ('office-and-stationery','Paper & Supplies','office-and-stationery-paper-and-supplies',1003),
    ('office-and-stationery','Office Tech','office-and-stationery-office-tech',1004),
    ('office-and-stationery','Filing & Storage','office-and-stationery-filing-and-storage',1005),
    ('office-and-stationery','Pens & Writing','office-and-stationery-pens-and-writing',1006),
    ('baby-and-nursery','Prams & Pushchairs','baby-and-nursery-prams-and-pushchairs',1101),
    ('baby-and-nursery','Baby Clothing','baby-and-nursery-baby-clothing',1102),
    ('baby-and-nursery','Feeding','baby-and-nursery-feeding',1103),
    ('baby-and-nursery','Nursery Furniture','baby-and-nursery-nursery-furniture',1104),
    ('baby-and-nursery','Toys (0-3 yrs)','baby-and-nursery-toys-0-3-yrs',1105),
    ('baby-and-nursery','Safety & Care','baby-and-nursery-safety-and-care',1106),
    ('jewellery-and-watches','Necklaces & Pendants','jewellery-and-watches-necklaces-and-pendants',1201),
    ('jewellery-and-watches','Rings & Earrings','jewellery-and-watches-rings-and-earrings',1202),
    ('jewellery-and-watches','Bracelets','jewellery-and-watches-bracelets',1203),
    ('jewellery-and-watches','Watches','jewellery-and-watches-watches',1204),
    ('jewellery-and-watches','Fashion Jewellery','jewellery-and-watches-fashion-jewellery',1205),
    ('jewellery-and-watches','Accessories','jewellery-and-watches-accessories',1206),
    ('mixed-lots','General Mixed','mixed-lots-general-mixed',1301),
    ('mixed-lots','Department Store Returns','mixed-lots-department-store-returns',1302),
    ('mixed-lots','Amazon Returns','mixed-lots-amazon-returns',1303),
    ('mixed-lots','Seasonal Mixed','mixed-lots-seasonal-mixed',1304),
    ('mixed-lots','High Value Mixed','mixed-lots-high-value-mixed',1305),
    ('mixed-lots','Liquidation Lots','mixed-lots-liquidation-lots',1306),
    ('customer-returns','Electronics Returns','customer-returns-electronics-returns',1401),
    ('customer-returns','Clothing Returns','customer-returns-clothing-returns',1402),
    ('customer-returns','Home Returns','customer-returns-home-returns',1403),
    ('customer-returns','Appliance Returns','customer-returns-appliance-returns',1404),
    ('customer-returns','Graded Returns','customer-returns-graded-returns',1405),
    ('customer-returns','Unchecked Returns','customer-returns-unchecked-returns',1406),
    ('overstock','Brand Overstock','overstock-brand-overstock',1501),
    ('overstock','Seasonal Overstock','overstock-seasonal-overstock',1502),
    ('overstock','End of Line','overstock-end-of-line',1503),
    ('overstock','Excess Inventory','overstock-excess-inventory',1504),
    ('overstock','Wholesale Lots','overstock-wholesale-lots',1505),
    ('overstock','Bulk Deals','overstock-bulk-deals',1506),
    ('clearance-deals','Flash Sales','clearance-deals-flash-sales',1601),
    ('clearance-deals','Closing Down Stock','clearance-deals-closing-down-stock',1602),
    ('clearance-deals','Damaged Packaging','clearance-deals-damaged-packaging',1603),
    ('clearance-deals','Short Dated','clearance-deals-short-dated',1604),
    ('clearance-deals','Sample Stock','clearance-deals-sample-stock',1605),
    ('clearance-deals','One-Off Deals','clearance-deals-one-off-deals',1606)
),
resolved AS (
  SELECT t.*, p.id AS parent_uuid
  FROM taxonomy t
  JOIN categories p ON p.slug = t.parent_slug
)
INSERT INTO categories (name, slug, description, "order", "isActive", level, parent_id, "parentId")
SELECT name, slug, name || ' — ' || parent_slug, sort_order, TRUE, 2, parent_uuid, parent_uuid
FROM resolved
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  "order" = EXCLUDED."order",
  "isActive" = TRUE,
  level = 2,
  parent_id = EXCLUDED.parent_id,
  "parentId" = EXCLUDED."parentId";

WITH canonical_children(slug) AS (
  VALUES
    ('electronics-and-technology-phones-and-tablets'),
    ('electronics-and-technology-laptops-and-pcs'),
    ('electronics-and-technology-tv-and-audio'),
    ('electronics-and-technology-gaming-consoles'),
    ('electronics-and-technology-accessories'),
    ('electronics-and-technology-smart-home'),
    ('clothing-and-apparel-men-s-clothing'),
    ('clothing-and-apparel-women-s-clothing'),
    ('clothing-and-apparel-children-s-clothing'),
    ('clothing-and-apparel-footwear'),
    ('clothing-and-apparel-accessories-and-bags'),
    ('clothing-and-apparel-sportswear'),
    ('home-and-garden-furniture'),
    ('home-and-garden-kitchen-and-dining'),
    ('home-and-garden-bedding-and-linen'),
    ('home-and-garden-garden-and-outdoor'),
    ('home-and-garden-lighting'),
    ('home-and-garden-d-cor-and-accessories'),
    ('health-and-beauty-skincare'),
    ('health-and-beauty-haircare'),
    ('health-and-beauty-makeup-and-cosmetics'),
    ('health-and-beauty-fragrances'),
    ('health-and-beauty-health-and-wellness'),
    ('health-and-beauty-personal-care'),
    ('toys-and-games-action-figures'),
    ('toys-and-games-board-games'),
    ('toys-and-games-educational-toys'),
    ('toys-and-games-outdoor-toys'),
    ('toys-and-games-dolls-and-playsets'),
    ('toys-and-games-puzzles'),
    ('food-and-drink-snacks-and-confectionery'),
    ('food-and-drink-beverages'),
    ('food-and-drink-canned-and-dry-goods'),
    ('food-and-drink-health-foods'),
    ('food-and-drink-specialty-and-gourmet'),
    ('food-and-drink-seasonal'),
    ('tools-and-diy-power-tools'),
    ('tools-and-diy-hand-tools'),
    ('tools-and-diy-plumbing'),
    ('tools-and-diy-electrical'),
    ('tools-and-diy-paint-and-decorating'),
    ('tools-and-diy-fixings-and-hardware'),
    ('sports-and-leisure-fitness-equipment'),
    ('sports-and-leisure-cycling'),
    ('sports-and-leisure-camping-and-hiking'),
    ('sports-and-leisure-water-sports'),
    ('sports-and-leisure-team-sports'),
    ('sports-and-leisure-leisure-and-travel'),
    ('automotive-car-parts'),
    ('automotive-car-accessories'),
    ('automotive-cleaning-and-valeting'),
    ('automotive-tools-and-equipment'),
    ('automotive-oils-and-fluids'),
    ('automotive-tyres-and-wheels'),
    ('office-and-stationery-office-furniture'),
    ('office-and-stationery-printers-and-ink'),
    ('office-and-stationery-paper-and-supplies'),
    ('office-and-stationery-office-tech'),
    ('office-and-stationery-filing-and-storage'),
    ('office-and-stationery-pens-and-writing'),
    ('baby-and-nursery-prams-and-pushchairs'),
    ('baby-and-nursery-baby-clothing'),
    ('baby-and-nursery-feeding'),
    ('baby-and-nursery-nursery-furniture'),
    ('baby-and-nursery-toys-0-3-yrs'),
    ('baby-and-nursery-safety-and-care'),
    ('jewellery-and-watches-necklaces-and-pendants'),
    ('jewellery-and-watches-rings-and-earrings'),
    ('jewellery-and-watches-bracelets'),
    ('jewellery-and-watches-watches'),
    ('jewellery-and-watches-fashion-jewellery'),
    ('jewellery-and-watches-accessories'),
    ('mixed-lots-general-mixed'),
    ('mixed-lots-department-store-returns'),
    ('mixed-lots-amazon-returns'),
    ('mixed-lots-seasonal-mixed'),
    ('mixed-lots-high-value-mixed'),
    ('mixed-lots-liquidation-lots'),
    ('customer-returns-electronics-returns'),
    ('customer-returns-clothing-returns'),
    ('customer-returns-home-returns'),
    ('customer-returns-appliance-returns'),
    ('customer-returns-graded-returns'),
    ('customer-returns-unchecked-returns'),
    ('overstock-brand-overstock'),
    ('overstock-seasonal-overstock'),
    ('overstock-end-of-line'),
    ('overstock-excess-inventory'),
    ('overstock-wholesale-lots'),
    ('overstock-bulk-deals'),
    ('clearance-deals-flash-sales'),
    ('clearance-deals-closing-down-stock'),
    ('clearance-deals-damaged-packaging'),
    ('clearance-deals-short-dated'),
    ('clearance-deals-sample-stock'),
    ('clearance-deals-one-off-deals')
)
UPDATE categories c
SET "isActive" = FALSE
WHERE COALESCE(c.level, 1) = 2
  AND c.slug NOT IN (SELECT slug FROM canonical_children)
  AND c.parent_id IN (
    SELECT id FROM categories WHERE slug = ANY (ARRAY['electronics-and-technology', 'clothing-and-apparel', 'home-and-garden', 'health-and-beauty', 'toys-and-games', 'food-and-drink', 'tools-and-diy', 'sports-and-leisure', 'automotive', 'office-and-stationery', 'baby-and-nursery', 'jewellery-and-watches', 'mixed-lots', 'customer-returns', 'overstock', 'clearance-deals']::text[])
  );
