import Stripe from 'stripe';
import { Handler } from '@netlify/functions';
import { createClient } from '@supabase/supabase-js';

// Fail gracefully if env vars not configured
if (!process.env.STRIPE_SECRET_KEY || !process.env.STRIPE_WEBHOOK_SECRET) {
  console.warn('Stripe webhook not configured - missing environment variables');
}

const stripe = process.env.STRIPE_SECRET_KEY 
  ? new Stripe(process.env.STRIPE_SECRET_KEY, {
      apiVersion: '2024-11-20.acacia',
    })
  : null;

const supabase = process.env.VITE_SUPABASE_URL && process.env.SUPABASE_SERVICE_ROLE_KEY
  ? createClient(
      process.env.VITE_SUPABASE_URL,
      process.env.SUPABASE_SERVICE_ROLE_KEY
    )
  : null;

export const handler: Handler = async (event) => {
  // Return 501 if not configured
  if (!stripe || !supabase || !process.env.STRIPE_WEBHOOK_SECRET) {
    return { 
      statusCode: 501, 
      body: JSON.stringify({ error: 'Stripe webhook not configured' })
    };
  }

  if (event.httpMethod !== 'POST') {
    return {
      statusCode: 405,
      body: JSON.stringify({ error: 'Method not allowed' }),
    };
  }

  const sig = event.headers['stripe-signature'];
  if (!sig) {
    return {
      statusCode: 400,
      body: JSON.stringify({ error: 'No signature' }),
    };
  }

  let stripeEvent: Stripe.Event;

  try {
    stripeEvent = stripe.webhooks.constructEvent(
      event.body!,
      sig,
      process.env.STRIPE_WEBHOOK_SECRET!
    );
  } catch (err) {
    console.error('Webhook signature verification failed:', err instanceof Error ? err.message : 'Unknown error');
    return {
      statusCode: 400,
      body: JSON.stringify({ error: `Webhook Error: ${err instanceof Error ? err.message : 'Unknown error'}` }),
    };
  }

  try {
    switch (stripeEvent.type) {
      case 'checkout.session.completed': {
        const session = stripeEvent.data.object as Stripe.Checkout.Session;
        await handleCheckoutCompleted(session);
        break;
      }

      case 'payment_intent.succeeded': {
        const paymentIntent = stripeEvent.data.object as Stripe.PaymentIntent;
        console.log('PaymentIntent succeeded:', paymentIntent.id);
        break;
      }

      case 'payment_intent.payment_failed': {
        const paymentIntent = stripeEvent.data.object as Stripe.PaymentIntent;
        console.error('PaymentIntent failed:', paymentIntent.id);
        break;
      }

      case 'charge.refunded': {
        const charge = stripeEvent.data.object as Stripe.Charge;
        await handleRefund(charge);
        break;
      }

      default:
        console.log(`Unhandled event type: ${stripeEvent.type}`);
    }

    return {
      statusCode: 200,
      body: JSON.stringify({ received: true }),
    };
  } catch (error) {
    console.error('Webhook handler error:', error);
    return {
      statusCode: 500,
      body: JSON.stringify({ error: error instanceof Error ? error.message : 'Unknown error' }),
    };
  }
};

async function handleCheckoutCompleted(session: Stripe.Checkout.Session) {
  const metadata = session.metadata!;

  // CartItem interface — matches what create-checkout serialises into metadata
  interface CartItem {
    productId: string;
    sellerId: string;
    quantity: number;
    price: number;
    title: string;
  }

  const items: CartItem[] = JSON.parse(metadata.items);
  const shippingAddress = JSON.parse(metadata.shippingAddress);
  const billingAddress = JSON.parse(metadata.billingAddress);

  // orders.productId is NOT NULL in the schema.
  // For multi-item orders we still create one order row (single-seller model)
  // and use the first item's productId as the primary product reference.
  const primaryItem = items[0];
  if (!primaryItem) throw new Error('Checkout metadata contains no items');

  // Create order — orderNumber is auto-generated by the DB sequence (LM-XXXXXXX)
  // so we deliberately omit it here to let Postgres fill it in.
  const { data: order, error: orderError } = await supabase
    .from('orders')
    .insert([
      {
        buyerId: metadata.buyerId || null,
        sellerId: primaryItem.sellerId,
        productId: primaryItem.productId,
        quantity: items.reduce((sum, i) => sum + i.quantity, 0),
        subtotal: parseFloat(metadata.subtotal),
        vatAmount: parseFloat(metadata.vatAmount),
        shippingAmount: parseFloat(metadata.shippingAmount || '0'),
        total: parseFloat(metadata.total),
        commission: parseFloat(metadata.commissionAmount),
        status: 'paid',
        shippingAddress,
        billingAddress,
        shippingMethod: metadata.shippingMethod || 'Standard',
      },
    ])
    .select()
    .single();

  if (orderError) {
    console.error('Error creating order:', orderError);
    throw orderError;
  }

  // Create order items — field names match the order_items schema:
  // pricePerUnit, vatRate, subtotal (no sellerId or lineTotal columns)
  const VAT_RATE = 0.2000;
  const orderItems = items.map((item) => ({
    orderId: order.id,
    productId: item.productId,
    quantity: item.quantity,
    pricePerUnit: item.price,
    vatRate: VAT_RATE,
    subtotal: item.price * item.quantity,
  }));

  const { error: itemsError } = await supabase
    .from('order_items')
    .insert(orderItems);

  if (itemsError) {
    console.error('Error creating order items:', itemsError);
    throw itemsError;
  }

  // Record the payment session — the schema table is payment_sessions, not payments.
  // Fields: stripeSessionId (unique), stripePaymentIntent, orderId, userId, amount, status
  await supabase.from('payment_sessions').insert([
    {
      orderId: order.id,
      userId: metadata.buyerId || null,
      stripeSessionId: session.id,
      stripePaymentIntent: session.payment_intent as string,
      amount: parseFloat(metadata.total),
      currency: 'GBP',
      status: 'completed',
      metadata: session,
    },
  ]);

  // Send confirmation email (async, don't wait)
  fetch(`${process.env.URL}/.netlify/functions/send-email`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      to: session.customer_email,
      subject: `Order Confirmation - ${orderNumber}`,
      template: 'order_confirmation',
      data: {
        customerName: 'Customer',
        orderNumber,
        orderDate: new Date().toLocaleDateString('en-GB'),
        total: parseFloat(metadata.total),
        items: (items as CartItem[]).map((item) => ({
          title: item.title,
          quantity: item.quantity,
          price: item.price,
        })),
      },
    }),
  }).catch(err => console.error('Email send failed:', err));

  // Generate invoice (async, don't wait)
  fetch(`${process.env.URL}/.netlify/functions/generate-invoice`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ orderId: order.id }),
  }).catch(err => console.error('Invoice generation failed:', err));

  console.log(`Order created successfully for session ${session.id}`);
}

interface PaymentSessionWithOrder {
  orderId: string;
  orders?: { orderNumber?: string } | null;
}

async function handleRefund(charge: Stripe.Charge) {
  const { data: payment } = await supabase
    .from('payment_sessions')
    .select('orderId, orders(orderNumber)')
    .eq('stripePaymentIntent', charge.payment_intent)
    .single<PaymentSessionWithOrder>();

  if (payment?.orderId) {
    await supabase
      .from('orders')
      .update({ status: 'refunded' })
      .eq('id', payment.orderId);

    const orderNumber = payment.orders?.orderNumber ?? payment.orderId;
    console.log(`Order ${orderNumber} refunded`);
  }
}
