/** update-product — authenticated seller/admin listing updates. */
import type { Handler } from '@netlify/functions';
import { createClient } from '@supabase/supabase-js';
import { authenticateActiveAccount } from './_shared/activeAccountAuth';
import { isMaintenanceMode } from './_shared/platformFlags';
import { checkRateLimit } from './_shared/rateLimiter';
import { buildSellerNonVatProductEvidence, hasExplicitSellerNonVatDeclaration, normaliseMarketplaceCountry } from './_shared/marketplaceTax';
import { deriveSellerListingLocks, formatSellerListingLockReason, SELLER_LISTING_LOCK_STATUSES } from '../../src/lib/listingLocks';

const LOCKED_CRITICAL_FIELDS = ['title','type','condition','price','listingContext','stockQuantity','stockStatus'] as const;
const UPDATE_ALLOWED_FIELDS = ['title','description','type','listingType','condition','price','categoryId','subcategoryId','listingContext','stockQuantity','stockStatus','images','specifications','weight','dimensions','palletInfo','logisticsInfo','isHandmade','isUnique','artistName','isActive'] as const;
function hasOwn(obj:Record<string,unknown>,key:string){return Object.prototype.hasOwnProperty.call(obj,key)}
function pickAllowedFields(src:Record<string,unknown>){const out:Record<string,unknown>={};for(const f of UPDATE_ALLOWED_FIELDS)if(hasOwn(src,f))out[f]=src[f];return out}
function parseStockQuantity(raw:unknown):number|null{if(typeof raw==='number')return Number.isInteger(raw)&&raw>=0?raw:null;if(typeof raw==='string'&&/^\d+$/.test(raw.trim()))return Number.parseInt(raw.trim(),10);return null}
function normaliseListingContext(v:unknown):'product'|'service'|null{if(v==='service')return'service';if(v==='product'||v==='goods')return'product';return null}
function calculateStockStatus(c:'product'|'service',q:number):'in_stock'|'low_stock'|'out_of_stock'{if(c==='service')return'in_stock';if(q>10)return'in_stock';if(q>0)return'low_stock';return'out_of_stock'}

export const handler: Handler = async(event)=>{
 if(event.httpMethod!=='POST')return{statusCode:405,body:JSON.stringify({error:'Method not allowed'})};
 const url=process.env.VITE_SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)return{statusCode:503,body:JSON.stringify({error:'Server misconfiguration'})};
 const supabase=createClient(url,key,{auth:{autoRefreshToken:false,persistSession:false}});
 const auth=await authenticateActiveAccount(event,supabase,['seller','admin']);if(!auth.ok)return{statusCode:auth.status,body:JSON.stringify({error:auth.status===401?'Authentication required':'Only active sellers can update listings'})};
 const callerId=auth.actor.id,isAdmin=auth.actor.role==='admin';
 const rl=await checkRateLimit({supabase,tableName:'update_product_rate_limits',identifier:callerId,windowMinutes:60,maxAttempts:60,policy:'fail-closed'});if(rl.exceeded)return{statusCode:429,body:JSON.stringify({error:'Too many listing updates. Please try again later.'})};
 if(await isMaintenanceMode(supabase)&&!isAdmin)return{statusCode:503,body:JSON.stringify({error:'Platform is temporarily under maintenance. Listings cannot be modified right now.'})};
 let body:Record<string,unknown>;try{body=JSON.parse(event.body||'{}')}catch{return{statusCode:400,body:JSON.stringify({error:'Invalid JSON body'})}};
 const {id:productId,shippingMethodIds,dispatchTime,lockedFieldsOnly,...updateFields}=body as{id:string;shippingMethodIds?:string[];dispatchTime?:string;lockedFieldsOnly?:boolean;[key:string]:unknown};if(!productId)return{statusCode:400,body:JSON.stringify({error:'"id" is required'})};

 const {data:existing,error:fetchError}=await supabase.from('products').select('sellerId, title, type, condition, price, priceExVat, vatRate, taxTreatmentStatus, taxTreatmentSource, taxEvidenceVersion, taxEvidenceCapturedAt, listingContext, stockQuantity, stockStatus, listingStatus, reservedUntil, isActive').eq('id',productId).maybeSingle<{sellerId:string;title:string|null;type:string|null;condition:string|null;price:number|null;priceExVat:number|null;vatRate:number|null;taxTreatmentStatus:string|null;taxTreatmentSource:string|null;taxEvidenceVersion:number|null;taxEvidenceCapturedAt:string|null;listingContext:string|null;stockQuantity:number|null;stockStatus:string|null;listingStatus:string|null;reservedUntil:string|null;isActive:boolean}>();
 if(fetchError||!existing)return{statusCode:404,body:JSON.stringify({error:'Product not found'})};if(!isAdmin&&existing.sellerId!==callerId)return{statusCode:403,body:JSON.stringify({error:'You do not have permission to edit this listing'})};
 let sellerCanPublish=isAdmin;if(!isAdmin){const {data:p,error}=await supabase.from('seller_profiles').select('sellerStatus, stripeConnectStatus, isPaused').eq('userId',callerId).maybeSingle<{sellerStatus:string|null;stripeConnectStatus:string|null;isPaused:boolean|null}>();if(error||!p)return{statusCode:409,body:JSON.stringify({error:'Complete your seller setup before updating listings.'})};sellerCanPublish=p.sellerStatus==='active'&&p.stripeConnectStatus==='active'&&p.isPaused!==true}

 const updateData=pickAllowedFields(updateFields);const nextContext=normaliseListingContext(hasOwn(updateData,'listingContext')?updateData.listingContext:existing.listingContext??'product');if(!nextContext)return{statusCode:400,body:JSON.stringify({error:'listingContext must be either "product" or "service"'})};if(hasOwn(updateData,'listingContext'))updateData.listingContext=nextContext;
 let nextPrice=existing.price;if(hasOwn(updateData,'price')){if(typeof updateData.price!=='number'||!Number.isFinite(updateData.price)||updateData.price<=0)return{statusCode:400,body:JSON.stringify({error:'price must be a positive number'})};nextPrice=updateData.price}if(typeof nextPrice!=='number'||!Number.isFinite(nextPrice)||nextPrice<=0)return{statusCode:409,body:JSON.stringify({error:'The listing has an invalid price and cannot be updated.'})};

 const {data:taxProfile,error:taxError}=await supabase.from('seller_profiles').select('country, isVatRegistered, vatNumber, businessAddress, taxDeclarationVersion, taxDeclarationSource, taxDeclarationCapturedAt').eq('userId',existing.sellerId).maybeSingle<{country:string|null;isVatRegistered:boolean|null;vatNumber:string|null;businessAddress:Record<string,unknown>|null;taxDeclarationVersion:number|null;taxDeclarationSource:string|null;taxDeclarationCapturedAt:string|null}>();if(taxError||!taxProfile)return{statusCode:500,body:JSON.stringify({error:'Unable to verify seller tax profile. Please try again.'})};
 const canUseNonVat=nextContext==='product'&&normaliseMarketplaceCountry(taxProfile.country)==='GB'&&hasExplicitSellerNonVatDeclaration(taxProfile);const taxEvidence=canUseNonVat?buildSellerNonVatProductEvidence(nextPrice):null;
 updateData.priceExVat=taxEvidence?.priceExVat??null;updateData.vatRate=taxEvidence?.vatRate??null;updateData.taxTreatmentStatus=taxEvidence?.taxTreatmentStatus??null;updateData.taxTreatmentSource=taxEvidence?.taxTreatmentSource??null;updateData.taxEvidenceVersion=taxEvidence?.taxEvidenceVersion??null;updateData.taxEvidenceCapturedAt=taxEvidence?.taxEvidenceCapturedAt??null;

 const stockProvided=hasOwn(updateData,'stockQuantity');let stock=existing.stockQuantity??0;if(nextContext==='service')stock=0;else if(stockProvided){const parsed=parseStockQuantity(updateData.stockQuantity);if(parsed===null)return{statusCode:400,body:JSON.stringify({error:'stockQuantity must be a whole number greater than or equal to 0'})};stock=parsed}if(hasOwn(updateData,'listingContext')||stockProvided||hasOwn(updateData,'stockStatus')){updateData.stockQuantity=stock;updateData.stockStatus=calculateStockStatus(nextContext,stock)}
 const wantsPublished=updateData.isActive===true||(!hasOwn(updateData,'isActive')&&existing.isActive);if(wantsPublished&&!sellerCanPublish)return{statusCode:409,body:JSON.stringify({error:'Complete seller setup and activate Stripe payments before publishing.'})};if(wantsPublished&&nextContext==='product'&&!taxEvidence)return{statusCode:409,body:JSON.stringify({error:'This listing cannot be published until the seller tax declaration is current and its VAT treatment is supported.',code:'TAX_EVIDENCE_REQUIRED'})};
 if(wantsPublished&&nextContext==='product'){let shippingCount=0;if(Array.isArray(shippingMethodIds))shippingCount=shippingMethodIds.length;else{const {count,error}=await supabase.from('product_shipping').select('product_id',{count:'exact',head:true}).eq('product_id',productId);if(error)return{statusCode:500,body:JSON.stringify({error:'Unable to validate shipping setup.'})};shippingCount=count??0}if(!shippingCount)return{statusCode:400,body:JSON.stringify({error:'Select at least one shipping method before publishing this product.'})}}

 const {data:orderLocks}=await supabase.from('orders').select('id, orderNumber, status, createdAt').eq('productId',productId).in('status',[...SELLER_LISTING_LOCK_STATUSES]);const locks=isAdmin?[]:deriveSellerListingLocks({orders:orderLocks??[],product:{listingStatus:existing.listingStatus??null,reservedUntil:existing.reservedUntil??null}});
 const criticalChanged=LOCKED_CRITICAL_FIELDS.some(field=>{if(!hasOwn(updateData,field))return false;const current=field==='listingContext'?normaliseListingContext(existing.listingContext??'product'):(existing as unknown as Record<string,unknown>)[field]??null;return updateData[field]!==current});if(!isAdmin&&locks.length&&criticalChanged)return{statusCode:409,body:JSON.stringify({error:`This listing is locked by ${formatSellerListingLockReason(locks)}.`,code:'LISTING_LOCKED',locks})};
 let dataToUpdate:Record<string,unknown>=updateData;if(lockedFieldsOnly&&locks.length&&!isAdmin){dataToUpdate={description:updateData.description,images:updateData.images,specifications:updateData.specifications,weight:updateData.weight,dimensions:updateData.dimensions,palletInfo:updateData.palletInfo};Object.keys(dataToUpdate).forEach(k=>{if(dataToUpdate[k]===undefined)delete dataToUpdate[k]})}
 if(Array.isArray(shippingMethodIds)){const {data:prev,error:prevError}=await supabase.from('product_shipping').select('method_id, dispatch_time').eq('product_id',productId);if(prevError)return{statusCode:500,body:JSON.stringify({error:'Unable to update shipping setup.'})};const {error:del}=await supabase.from('product_shipping').delete().eq('product_id',productId);if(del)return{statusCode:500,body:JSON.stringify({error:'Unable to update shipping setup.'})};if(shippingMethodIds.length){const rows=shippingMethodIds.map(method_id=>({product_id:productId,method_id,dispatch_time:dispatchTime||null}));const {error}=await supabase.from('product_shipping').insert(rows);if(error){if(prev?.length)await supabase.from('product_shipping').insert(prev.map(r=>({product_id:productId,method_id:r.method_id,dispatch_time:r.dispatch_time})));return{statusCode:500,body:JSON.stringify({error:'Shipping setup could not be saved; listing changes were not applied.'})}}}
 if(Object.keys(dataToUpdate).length){const {error}=await supabase.from('products').update(dataToUpdate).eq('id',productId);if(error)return{statusCode:500,body:JSON.stringify({error:'Failed to update listing. Please try again.'})}}
 return{statusCode:200,body:JSON.stringify({id:productId})};
};
