[build]
  publish = "."
  functions = "functions"

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from="/*"
  to="/404.html"
  status=404

[[headers]]
  for="/*"
  [headers.values]
    X-Frame-Options="DENY"
    X-Content-Type-Options="nosniff"
    Referrer-Policy="no-referrer-when-downgrade"
