import { Link } from "react-router-dom";
import { ArrowRight, Boxes, CheckCircle2, ClipboardList, CreditCard, PackageCheck, Search, ShieldCheck, Store, Truck } from "lucide-react";
import MainLayout from "@/layouts/MainLayout";
import SEO from "@/components/SEO";

const buyerFlow = [
  { icon: Search, eyebrow: "DISCOVER", title: "Discover", copy: "Browse categories, search the catalogue and open product pages to understand the offer." },
  { icon: Boxes, eyebrow: "CHOOSE", title: "Choose", copy: "Review product information and the marketplace seller context before adding products to your cart." },
  { icon: CreditCard, eyebrow: "CHECKOUT", title: "Checkout", copy: "Complete the supported marketplace checkout through Loadify's Stripe-backed payment flow." },
  { icon: Truck, eyebrow: "TRACK", title: "Track", copy: "Follow order progress and use tracking information where it has been provided for the shipment." },
] as const;

const sellerFlow = [
  ["01", "Register", "Create a seller account through the dedicated seller registration path."],
  ["02", "Complete setup", "Complete the applicable business, marketplace-readiness and payment setup requirements."],
  ["03", "List products", "Create accurate marketplace listings with authoritative product, price and stock information."],
  ["04", "Manage orders", "Use the seller workspace for orders, shipments, returns, reviews, messages and other supported operations."],
] as const;

export default function HowItWorksPage() {
  return (
    <MainLayout>
      <SEO title="How Loadify Market Works | Buyers, Sellers & Marketplace Operations" description="See how buyers discover and order products, how sellers manage marketplace commerce, and how Loadify connects the customer and seller journey." canonical="/how-it-works" />
      <main id="main-content" className="bg-[#F8F7F4] text-[#0A234F] md:pt-[122px]">
        <section className="border-b border-[#0A234F]/10"><div className="mx-auto max-w-[1480px] px-5 py-16 text-center sm:px-7 lg:px-10 lg:py-24"><p className="text-[11px] font-extrabold uppercase tracking-[0.2em] text-[#8A7351]">How Loadify works</p><h1 className="mx-auto mt-5 max-w-[980px] font-serif text-[2.75rem] font-normal leading-[1.02] tracking-[-0.04em] sm:text-[3.8rem] lg:text-[4.5rem]">One marketplace journey, with clear paths for buyers and sellers.</h1><p className="mx-auto mt-7 max-w-[800px] text-[16px] leading-7 text-[#5A6578] sm:text-[18px] sm:leading-8">Customers discover and order through Loadify. Sellers manage the marketplace operations required to progress those orders. Account, payment, support and governance controls connect the two sides.</p><div className="mt-8 flex flex-wrap justify-center gap-3"><Link to="/catalog" className="inline-flex min-h-12 items-center gap-2 rounded-lg bg-[#0A234F] px-6 py-3 text-sm font-bold text-white">Browse marketplace <ArrowRight className="h-4 w-4" /></Link><Link to="/register?type=seller" className="inline-flex min-h-12 items-center rounded-lg border border-[#0A234F]/15 bg-white px-6 py-3 text-sm font-bold text-[#0A234F]">Start selling</Link></div></div></section>

        <section className="bg-white py-16 sm:py-20"><div className="mx-auto max-w-[1480px] px-5 sm:px-7 lg:px-10"><div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><p className="text-[10px] font-black uppercase tracking-[0.18em] text-[#8A7351]">For buyers</p><h2 className="mt-3 max-w-3xl font-serif text-3xl tracking-[-0.025em] sm:text-4xl">From discovery to delivery visibility.</h2></div><Link to="/buyers" className="inline-flex items-center gap-2 text-sm font-extrabold">Explore buyer experience <ArrowRight className="h-4 w-4" /></Link></div><div className="mt-10 grid gap-5 md:grid-cols-2 xl:grid-cols-4">{buyerFlow.map(({icon:Icon,eyebrow,title,copy}) => <article key={title} className="rounded-[24px] bg-[#0A234F] p-7 text-white shadow-[0_18px_50px_rgba(10,35,79,0.12)]"><Icon className="h-6 w-6 text-[#F5A300]" /><p className="mt-6 text-[10px] font-black uppercase tracking-[0.18em] text-[#F5A300]">{eyebrow}</p><h3 className="mt-3 font-serif text-[1.8rem] font-normal leading-[1.08] tracking-[-0.03em] text-white">{title}</h3><p className="mt-4 text-[15px] leading-7 text-white/80">{copy}</p></article>)}</div></div></section>

        <section className="bg-[#F7F9FC] py-16 sm:py-20"><div className="mx-auto grid max-w-[1480px] gap-10 px-5 sm:px-7 lg:grid-cols-[0.8fr_1.2fr] lg:px-10"><div><Store className="h-6 w-6 text-[#8A7351]" /><p className="mt-5 text-[10px] font-black uppercase tracking-[0.18em] text-[#8A7351]">For sellers</p><h2 className="mt-3 font-serif text-3xl tracking-[-0.025em] sm:text-4xl">Set up, list and operate your marketplace presence.</h2><p className="mt-4 max-w-xl text-sm leading-7 text-[#667085]">Registration, readiness and day-to-day commerce are distinct stages. Loadify's seller environment brings the supported operating tools together.</p><Link to="/sellers" className="mt-6 inline-flex items-center gap-2 text-sm font-extrabold">Explore seller experience <ArrowRight className="h-4 w-4" /></Link></div><div className="overflow-hidden rounded-[24px] bg-[#0A234F] text-white shadow-[0_18px_50px_rgba(10,35,79,0.12)]">{sellerFlow.map(([step,title,copy]) => <div key={step} className="grid gap-2 border-b border-white/10 p-6 last:border-0 sm:grid-cols-[55px_170px_1fr]"><span className="text-[11px] font-black tracking-[0.16em] text-[#F5A300]">{step}</span><h3 className="font-serif text-xl font-normal text-white">{title}</h3><p className="text-sm leading-6 text-white/75">{copy}</p></div>)}</div></div></section>

        <section className="bg-white py-16 sm:py-20"><div className="mx-auto max-w-[1280px] px-5 sm:px-7 lg:px-10"><div className="grid gap-5 md:grid-cols-3"><article className="rounded-[24px] bg-[#0A234F] p-8 text-white shadow-[0_18px_50px_rgba(10,35,79,0.12)]"><PackageCheck className="h-6 w-6 text-[#F5A300]" /><p className="mt-6 text-[10px] font-black uppercase tracking-[0.18em] text-[#F5A300]">OPERATIONS</p><h2 className="mt-3 font-serif text-[1.9rem] font-normal leading-[1.08] tracking-[-0.03em] text-white">Order operations</h2><p className="mt-4 text-[15px] leading-7 text-white/80">Buyer and seller order views support the two sides of marketplace order management.</p></article><article className="rounded-[24px] bg-[#0A234F] p-8 text-white shadow-[0_18px_50px_rgba(10,35,79,0.12)]"><ClipboardList className="h-6 w-6 text-[#F5A300]" /><p className="mt-6 text-[10px] font-black uppercase tracking-[0.18em] text-[#F5A300]">WORKSPACES</p><h2 className="mt-3 font-serif text-[1.9rem] font-normal leading-[1.08] tracking-[-0.03em] text-white">Account workspaces</h2><p className="mt-4 text-[15px] leading-7 text-white/80">Dedicated buyer and seller environments keep role-specific commerce activity organised.</p></article><article className="rounded-[24px] bg-[#0A234F] p-8 text-white shadow-[0_18px_50px_rgba(10,35,79,0.12)]"><ShieldCheck className="h-6 w-6 text-[#F5A300]" /><p className="mt-6 text-[10px] font-black uppercase tracking-[0.18em] text-[#F5A300]">GOVERNANCE</p><h2 className="mt-3 font-serif text-[1.9rem] font-normal leading-[1.08] tracking-[-0.03em] text-white">Marketplace governance</h2><p className="mt-4 text-[15px] leading-7 text-white/80">Policies, role-aware controls, seller readiness and evidence-gated integrations provide operating boundaries around the marketplace.</p></article></div></div></section>

        <section className="bg-[#0A234F] py-16 text-white sm:py-20"><div className="mx-auto max-w-[1180px] px-5 text-center sm:px-7"><CheckCircle2 className="mx-auto h-6 w-6 text-[#F5A300]" /><h2 className="mx-auto mt-4 max-w-3xl font-serif text-3xl tracking-[-0.025em] sm:text-4xl">Choose the Loadify path that fits what you need to do.</h2><div className="mt-7 flex flex-wrap justify-center gap-3"><Link to="/buyers" className="inline-flex min-h-12 items-center rounded-lg bg-[#F5A300] px-6 py-3 text-sm font-extrabold text-[#0A234F]">For buyers</Link><Link to="/sellers" className="inline-flex min-h-12 items-center rounded-lg border border-white/20 px-6 py-3 text-sm font-bold text-white">For sellers</Link><Link to="/trade" className="inline-flex min-h-12 items-center rounded-lg border border-white/20 px-6 py-3 text-sm font-bold text-white">For trade buyers</Link></div></div></section>
      </main>
    </MainLayout>
  );
}
